  #服务端口号
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka/
spring:
  cloud:
    inetutils:
      use-only-site-local-interfaces: true

